// models/Product.js
// The core collection of the whole system.
// `status` is NOT set manually by the user - it is automatically calculated
// from `quantity` vs `lowStockThreshold` every time the product is saved.
//
// PHASE 6: `sku` and `barcode` are auto-generated by the backend (see the
// static helpers below + productController.js's createProduct) rather than
// typed in by the user, per the spec: "Every product should automatically
// receive: unique SKU, unique barcode." `image` is optional and populated
// later via POST /products/:id/image (same pattern as the user profile
// photo upload), since a brand-new product doesn't have an id/file yet.

const mongoose = require('mongoose');

const productSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, 'Product name is required'],
      trim: true,
    },
    sku: {
      type: String,
      required: [true, 'SKU is required'],
      unique: true,
      trim: true,
      uppercase: true,
    },
    // PHASE 6: unique product barcode, auto-generated on creation.
    // `sparse: true` means multiple documents can have no barcode (e.g.
    // any pre-Phase-6 data) without violating the unique index - only
    // documents that DO have a barcode value need to be distinct.
    barcode: {
      type: String,
      unique: true,
      sparse: true,
      trim: true,
    },
    // PHASE 6: relative URL path to an uploaded product photo, e.g.
    // "/uploads/product-photos/abc123.jpg". Empty string until a photo is
    // uploaded - the frontend shows a placeholder icon in that case.
    image: {
      type: String,
      default: '',
    },
    category: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Category',
      required: [true, 'Category is required'],
    },
    quantity: {
      type: Number,
      required: true,
      min: [0, 'Quantity cannot be negative'],
      default: 0,
    },
    price: {
      type: Number,
      required: [true, 'Price is required'],
      min: [0, 'Price cannot be negative'],
    },
    supplier: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Supplier',
      required: [true, 'Supplier is required'],
    },
    lowStockThreshold: {
      type: Number,
      required: true,
      min: [0, 'Threshold cannot be negative'],
      default: 10,
    },
    // Automatically derived - see pre('save') hook below.
    status: {
      type: String,
      enum: ['In Stock', 'Low Stock', 'Out of Stock'],
      default: 'In Stock',
    },
  },
  { timestamps: true }
);

// PHASE 6: builds a human-readable SKU like "ELEC-MOB-0001" from the
// category name + product name, e.g. category "Electronics" + name
// "Mobile Phone" -> prefix "ELEC", midfix "MOB". `sequence` is whatever
// number the caller supplies (productController.js works out the next
// free one) - this function only formats it, it doesn't touch the DB.
productSchema.statics.buildSkuCandidate = function (categoryName, productName, sequence) {
  const clean = (str, maxLen) =>
    (str || '')
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '')
      .padEnd(maxLen, 'X')
      .slice(0, maxLen);
  const categoryPrefix = clean(categoryName, 4) || 'GEN';
  const namePrefix = clean(productName, 3) || 'PRD';
  const paddedSequence = String(sequence).padStart(4, '0');
  return `${categoryPrefix}-${namePrefix}-${paddedSequence}`;
};

// PHASE 6: builds a purely numeric barcode candidate. Not a "real"
// EAN/UPC checksum-verified barcode - just a unique-looking numeric
// string, which is all this project needs for search/scanning purposes.
productSchema.statics.buildBarcodeCandidate = function () {
  const timestampPart = Date.now().toString().slice(-10); // last 10 digits of the current ms timestamp
  const randomPart = Math.floor(100 + Math.random() * 900); // 3 random digits
  return `${timestampPart}${randomPart}`;
};

// Shared logic so both the pre-save hook AND stock update endpoints
// (Phase 4) can recalculate status consistently.
productSchema.methods.calculateStatus = function () {
  if (this.quantity <= 0) return 'Out of Stock';
  if (this.quantity <= this.lowStockThreshold) return 'Low Stock';
  return 'In Stock';
};

// Runs before every save - keeps `status` always in sync with quantity.
productSchema.pre('save', function () {
  this.status = this.calculateStatus();
});

// PHASE 7: Runs AFTER every save - keeps the StockAlert collection in sync
// with the product's status. This is the single place alert creation
// happens, so it doesn't matter whether the stock changed via creating a
// product, editing it, or the increase/decrease-stock endpoints - the
// alert logic is always applied consistently.
//
// - If the product is now Low Stock or Out of Stock, make sure there's an
//   active alert for it (create one if missing, otherwise refresh its
//   message so the quantity mentioned stays current).
// - If the product is back to In Stock, auto-resolve any active alerts.
//
// PHASE 3: also creates a Notification (for the bell icon), but ONLY when
// a NEW alert is created - not on every message refresh - so Admins/
// Managers don't get spammed with a fresh notification on every single
// stock adjustment while a product stays low.
productSchema.post('save', async function (doc) {
  try {
    // Required here (not at the top of the file) to avoid a circular
    // require between Product.js and StockAlert.js/Notification.js.
    const StockAlert = require('./StockAlert');
    const createNotification = require('../utils/createNotification');

    if (doc.status === 'Low Stock' || doc.status === 'Out of Stock') {
      const message = `"${doc.name}" is ${doc.status} (quantity: ${doc.quantity}, threshold: ${doc.lowStockThreshold})`;
      const existingActive = await StockAlert.findOne({ product: doc._id, status: 'active' });

      if (existingActive) {
        existingActive.message = message; // keep the quantity mentioned up to date
        await existingActive.save();
      } else {
        await StockAlert.create({ product: doc._id, message, status: 'active' });
        // Notify Admin + Manager (who both have inventory oversight per
        // the permission map) - a genuinely NEW low-stock situation.
        const notifType = doc.status === 'Out of Stock' ? 'out_of_stock' : 'low_stock';
        await createNotification('admin', notifType, message, '/alerts');
        await createNotification('manager', notifType, message, '/alerts');
      }
    } else {
      // Status is 'In Stock' - resolve any alerts that were open for this product
      await StockAlert.updateMany(
        { product: doc._id, status: 'active' },
        { status: 'resolved' }
      );
    }
  } catch (error) {
    // Never let alert-syncing break the actual product save.
    console.error('Failed to sync stock alert:', error.message);
  }
});

module.exports = mongoose.model('Product', productSchema);
